version: '3'

services:
  hadoop-master:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-master
    environment:
      - CLUSTER_NAME=test
      - HDFS_NAMENODE=true
    ports:
      - "50070:50070"
    networks:
      - hadoop_net

  hadoop-datanode1:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-datanode1
    environment:
      - CLUSTER_NAME=test
      - HDFS_DATANODE=true
    networks:
      - hadoop_net

  hadoop-datanode2:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-datanode2
    environment:
      - CLUSTER_NAME=test
      - HDFS_DATANODE=true
    networks:
      - hadoop_net

  # MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - hadoop_net

  # Hive
  hive-server:
    image: hive:latest
    ports:
      - "10000:10000"
    networks:
      - hadoop_net

  # Phoenix
  phoenix-server:
    image: apache/phoenix:latest
    ports:
      - "8765:8765"
    networks:
      - hadoop_net

  # Superset
  superset:
    image: apache/superset
    ports:
      - "8088:8088"
    networks:
      - hadoop_net

  # Zeppelin
  zeppelin:
    image: apache/zeppelin
    ports:
      - "8080:8080"
    networks:
      - hadoop_net

networks:
  hadoop_net:
    driver: bridge
