version: '3'

services:
  # Zookeeper (para coordenação)
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
    ports:
      - "2181:2181"
    networks:
      - hadoop-network
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  # HDFS NameNode (Main Server)
  hadoop-namenode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: MainServer
    command: /etc/bootstrap.sh -d
    environment:
      HDFS_CONF_dfs_namenode_rpc_address: "MainServer:9000"
      HDFS_CONF_dfs_namenode_http_address: "MainServer:50070"
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
    networks:
      - hadoop-network
    depends_on:
      - zookeeper

  # HDFS DataNode (Server1)
  hadoop-datanode1:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: Server1
    command: /etc/bootstrap.sh -d
    environment:
      HDFS_CONF_dfs_datanode_data_dir: "/hadoop/dfs/data"
    ports:
      - "50075:50075"
    volumes:
      - hdfs-datanode1:/hadoop/dfs/data
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode

  # HDFS DataNode (Server2)
  hadoop-datanode2:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: Server2
    command: /etc/bootstrap.sh -d
    environment:
      HDFS_CONF_dfs_datanode_data_dir: "/hadoop/dfs/data"
    ports:
      - "50076:50075"
    volumes:
      - hdfs-datanode2:/hadoop/dfs/data
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode

  # YARN ResourceManager (MainServer)
  yarn-resourcemanager:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: yarn-resourcemanager
    environment:
      YARN_CONF_yarn_resourcemanager_hostname: "MainServer"
      YARN_CONF_yarn_resourcemanager_address: "MainServer:8032"
    ports:
      - "8088:8088"
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode

  # YARN NodeManager (Server1)
  yarn-nodemanager1:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: yarn-nodemanager1
    environment:
      YARN_CONF_yarn_nodemanager_local_dirs: "/tmp/hadoop-yarn"
    networks:
      - hadoop-network
    depends_on:
      - yarn-resourcemanager

  # YARN NodeManager (Server2)
  yarn-nodemanager2:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: yarn-nodemanager2
    environment:
      YARN_CONF_yarn_nodemanager_local_dirs: "/tmp/hadoop-yarn"
    networks:
      - hadoop-network
    depends_on:
      - yarn-resourcemanager

  # HBase
  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    environment:
      HBASE_MASTER: "MainServer"
    ports:
      - "16010:16010"
    networks:
      - hadoop-network
    depends_on:
      - zookeeper

  # Phoenix (SQL interface for HBase)
  phoenix:
    image: cloudera/phoenix:latest
    container_name: phoenix
    ports:
      - "8765:8765"
    networks:
      - hadoop-network
    depends_on:
      - hbase

  # Hive Server2
  hive-server2:
    image: bde2020/hive:latest
    container_name: hive-server2
    environment:
      HIVE_METASTORE_URI: "thrift://hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode
      - hbase

  # Hue (Web interface for Hadoop)
  hue:
    image: cloudera/hue:latest
    container_name: hue
    environment:
      HUE_DATABASE_URL: "jdbc:mysql://hue-mysql:3306/hue"
    ports:
      - "8888:8888"
    networks:
      - hadoop-network
    depends_on:
      - hive-server2

  # Apache2 (HTTP server for web access)
  apache2:
    image: httpd:2.4
    container_name: apache2
    ports:
      - "80:80"
    networks:
      - hadoop-network

  # Zeppelin (Web-based notebook for interactive data analysis)
  zeppelin:
    image: apache/zeppelin:latest
    container_name: zeppelin
    environment:
      ZEPPELIN_NOTEBOOK_DIR: "/notebooks"
    ports:
      - "8080:8080"
    networks:
      - hadoop-network
    depends_on:
      - hive-server2

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge

volumes:
  zookeeper-data:
  zookeeper-datalog:
  hdfs-namenode:
  hdfs-datanode1:
  hdfs-datanode2:
