version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
    ports:
      - "2181:2181"
    networks:
      - hadoop-network

  hadoop-namenode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-namenode
    command: /etc/bootstrap.sh -d
    environment:
      HDFS_CONF_dfs_namenode_rpc_address: "namenode:9000"
      HDFS_CONF_dfs_namenode_http_address: "namenode:50070"
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
    networks:
      - hadoop-network
    depends_on:
      - zookeeper

  hadoop-datanode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-datanode
    command: /etc/bootstrap.sh -d
    environment:
      HDFS_CONF_dfs_datanode_data_dir: "/hadoop/dfs/data"
    ports:
      - "50075:50075"
    volumes:
      - hdfs-datanode:/hadoop/dfs/data
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode

  yarn-resourcemanager:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: yarn-resourcemanager
    environment:
      YARN_CONF_yarn_resourcemanager_hostname: "resourcemanager"
      YARN_CONF_yarn_resourcemanager_address: "resourcemanager:8032"
    ports:
      - "8088:8088"
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode

  yarn-nodemanager:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: yarn-nodemanager
    environment:
      YARN_CONF_yarn_nodemanager_local_dirs: "/tmp/hadoop-yarn"
    networks:
      - hadoop-network
    depends_on:
      - yarn-resourcemanager

  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    environment:
      HBASE_MASTER: "hbase-master"
    ports:
      - "16010:16010"
    networks:
      - hadoop-network
    depends_on:
      - zookeeper

  phoenix:
    image: cloudera/phoenix:latest
    container_name: phoenix
    ports:
      - "8765:8765"
    networks:
      - hadoop-network
    depends_on:
      - hbase

  hive-server2:
    image: bde2020/hive:latest
    container_name: hive-server2
    environment:
      HIVE_METASTORE_URI: "thrift://hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode
      - hbase

  hue:
    image: cloudera/hue:latest
    container_name: hue
    environment:
      HUE_DATABASE_URL: "jdbc:mysql://hue-mysql:3306/hue"
    ports:
      - "8888:8888"
    networks:
      - hadoop-network
    depends_on:
      - hive-server2

  apache2:
    image: httpd:2.4
    container_name: apache2
    ports:
      - "80:80"
    networks:
      - hadoop-network

  zeppelin:
    image: apache/zeppelin:latest
    container_name: zeppelin
    environment:
      ZEPPELIN_NOTEBOOK_DIR: "/notebooks"
    ports:
      - "8080:8080"
    networks:
      - hadoop-network
    depends_on:
      - hive-server2

networks:
  hadoop-network:
    driver: bridge

volumes:
  hdfs-namenode:
  hdfs-datanode:
